# Generated by Django 4.1.1 on 2023-02-07 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=255, verbose_name='lastname')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('notes', models.TextField(default=None, max_length=250, verbose_name='notes')),
                ('shipping', models.BooleanField(blank=True, default=False, null=True, verbose_name='shipping')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('status', models.CharField(blank=True, choices=[('processing', 'processing'), ('awaiting payment', 'awaiting payment'), ('ready for getting', 'ready for getting'), ('delivered', 'delivered'), ('rejected', 'rejected')], max_length=40, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='coupon.coupon')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.product')),
            ],
        ),
    ]
