version: '3.7'

services:
  app:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    container_name: app
    hostname: app
    expose: ['8080']
    env_file:
      - ../.env/prod.env
    networks:
      backend:
        aliases:
          - app

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ../staticfiles:/var/www/backwood/static/
      - ../media:/var/www/backwood/media/
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt/
    environment:
      - DOMAIN=backwood.online
      - IP=84.23.54.118
    networks:
        backend:
          aliases:
            - nginx

networks:
  backend:
    name: backend_network