# Generated by Django 4.1.1 on 2023-02-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageHitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='url')),
                ('count', models.PositiveBigIntegerField(default=0, verbose_name='count')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_url', models.URLField(blank=True, null=True, verbose_name='absolute url')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_categories')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='description')),
                ('notes', models.CharField(blank=True, max_length=64, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_url', models.URLField(blank=True, null=True, verbose_name='absolute url')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('name_singular', models.CharField(max_length=40, unique=True, verbose_name='name singular')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='products_types')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='description')),
                ('notes', models.CharField(blank=True, max_length=64, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'product type',
                'verbose_name_plural': 'product types',
            },
        ),
        migrations.CreateModel(
            name='ProductSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_url', models.URLField(blank=True, null=True, verbose_name='absolute url')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('name_singular', models.CharField(max_length=40, unique=True, verbose_name='name singular')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('image', models.ImageField(blank=True, upload_to='products_subtypes')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='description')),
                ('notes', models.CharField(blank=True, max_length=64, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producttype')),
            ],
            options={
                'verbose_name': 'product subtype',
                'verbose_name_plural': 'product subtypes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_url', models.URLField(blank=True, null=True, verbose_name='absolute url')),
                ('sku', models.CharField(blank=True, editable=False, max_length=124, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=124, unique=True, verbose_name='name')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images')),
                ('image_second', models.ImageField(blank=True, null=True, upload_to='products_images')),
                ('colour', models.CharField(blank=True, choices=[('#BEBEBE', 'grey'), ('#0000FF', 'blue'), ('#00FF00', 'green'), ('#FFC0CB', 'pink'), ('#EEEE00', 'yellow'), ('#F5F5DC', 'beige'), ('#FFD39B', 'light wood'), ('#8B7355', 'dark wood'), ('#000000', 'black'), ('#FFFFFF', 'white'), ('#FFE4C4', 'bisque'), ('#BDB76B', 'dark khaki'), ('#DEB887', 'burlywood'), ('#CDC8B1', 'cornsilk')], max_length=40, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price')),
                ('is_discount', models.BooleanField(blank=True, default=False, null=True, verbose_name='discount')),
                ('sum_discount', models.PositiveIntegerField(blank=True, choices=[(5, 5), (10, 10), (15, 15), (20, 20)], null=True, verbose_name='sum discount')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='active')),
                ('short_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='short description')),
                ('description', models.TextField(blank=True, max_length=960, null=True, verbose_name='description')),
                ('notes', models.CharField(blank=True, max_length=64, null=True, verbose_name='notes')),
                ('product_dimensions', models.CharField(blank=True, max_length=40, null=True, verbose_name='product dimensions')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='weight')),
                ('packaging_dimensions', models.CharField(blank=True, max_length=128, null=True, verbose_name='packaging dimensions')),
                ('country', models.CharField(blank=True, choices=[('italy', 'italy'), ('germany', 'germany'), ('switzerland', 'switzerland'), ('portugal', 'switzerland'), ('poland', 'poland'), ('england', 'england')], max_length=40, null=True, verbose_name='country')),
                ('warranty', models.PositiveIntegerField(blank=True, choices=[(12, '12'), (24, '24'), (36, '36'), (48, '48')], null=True, verbose_name='warranty in month')),
                ('recommended_load', models.PositiveIntegerField(blank=True, null=True, verbose_name='recommended load')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productcategory')),
                ('product_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.productsubtype')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.producttype')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'sku', 'is_discount'], name='main_produc_name_f3490b_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'sku'), name=' main_product_title_price_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'created_at', 'image'), ('name', 'sku', 'created_at', 'image'), ('name', 'colour', 'product_sub_type'), ('name', 'sku'), ('name', 'image')},
        ),
    ]
